// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/data/models/attendance_entity.dart';
import 'core/data/models/habit_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4696534318746626837),
      name: 'Attendance',
      lastPropertyId: const obx_int.IdUid(3, 1984469243369246329),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5032875524434865996),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6924529895095687989),
            name: 'habitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 6101209311534201428),
            relationTarget: 'HabitE'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1984469243369246329),
            name: 'date',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 6261482500708783295),
      name: 'HabitE',
      lastPropertyId: const obx_int.IdUid(5, 1391790752647117719),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3813943266049296277),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2388505740743741768),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4970332623146630218),
            name: 'createdDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3966561964410598251),
            name: 'startDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1391790752647117719),
            name: 'endDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 6261482500708783295),
      lastIndexId: const obx_int.IdUid(1, 6101209311534201428),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4404611071443216341],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6455932149684917762,
        5349050313806359004,
        1177153255038861064,
        1428138875203036309
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Attendance: obx_int.EntityDefinition<Attendance>(
        model: _entities[0],
        toOneRelations: (Attendance object) => [object.habit],
        toManyRelations: (Attendance object) => {},
        getId: (Attendance object) => object.id,
        setId: (Attendance object, int id) {
          object.id = id;
        },
        objectToFB: (Attendance object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.habit.targetId);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final object = Attendance(id: idParam, date: dateParam);
          object.habit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.habit.attach(store);
          return object;
        }),
    HabitE: obx_int.EntityDefinition<HabitE>(
        model: _entities[1],
        toOneRelations: (HabitE object) => [],
        toManyRelations: (HabitE object) => {},
        getId: (HabitE object) => object.id,
        setId: (HabitE object, int id) {
          object.id = id;
        },
        objectToFB: (HabitE object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.createdDate?.millisecondsSinceEpoch);
          fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
          fbb.addInt64(4, object.endDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final endDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final startDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final endDateParam = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue);
          final object = HabitE(
              id: idParam,
              name: nameParam,
              startDate: startDateParam,
              endDate: endDateParam)
            ..createdDate = createdDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdDateValue);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Attendance] entity fields to define ObjectBox queries.
class Attendance_ {
  /// See [Attendance.id].
  static final id =
      obx.QueryIntegerProperty<Attendance>(_entities[0].properties[0]);

  /// See [Attendance.habit].
  static final habit =
      obx.QueryRelationToOne<Attendance, HabitE>(_entities[0].properties[1]);

  /// See [Attendance.date].
  static final date =
      obx.QueryDateProperty<Attendance>(_entities[0].properties[2]);
}

/// [HabitE] entity fields to define ObjectBox queries.
class HabitE_ {
  /// See [HabitE.id].
  static final id =
      obx.QueryIntegerProperty<HabitE>(_entities[1].properties[0]);

  /// See [HabitE.name].
  static final name =
      obx.QueryStringProperty<HabitE>(_entities[1].properties[1]);

  /// See [HabitE.createdDate].
  static final createdDate =
      obx.QueryDateProperty<HabitE>(_entities[1].properties[2]);

  /// See [HabitE.startDate].
  static final startDate =
      obx.QueryDateProperty<HabitE>(_entities[1].properties[3]);

  /// See [HabitE.endDate].
  static final endDate =
      obx.QueryDateProperty<HabitE>(_entities[1].properties[4]);
}
